/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApplicationClient: typeof import('./src/components/ApplicationClient.vue')['default']
    CreateClient: typeof import('./src/components/CreateClient.vue')['default']
    CreatePosition: typeof import('./src/components/CreatePosition.vue')['default']
    PositionSearch: typeof import('./src/components/PositionSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
